path: .
train: smoke/c3/p2/config/splits/deeppcb_10_seed824.txt
val: datasets/deeppcb_yolo/images/val
test: datasets/deeppcb_yolo/images/test
names:
  0: open
  1: short
  2: mousebite
  3: spur
  4: copper
  5: pin-hole
